stages:
  - test

test:
  stage: test
  image: gradle:8.5-jdk17
  script:
    - gradle test
  artifacts:
    reports:
      junit: build/test-results/test/*.xml
    paths:
      - build/reports/
  only:
    - merge_requests
    - main
    - master
