package com.gbujak.kanalarz;

import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;

/**
 * Persistence adapter used by Kanalarz to store and query step execution history.
 * <p>
 * Correctness of rollback and resume replay depends on this adapter returning consistent data.
 * The expected lifecycle for each step execution is:
 * <ol>
 *     <li>{@link #stepStarted(StepStartedEvent)} is called before user code executes the step.</li>
 *     <li>{@link #stepCompleted(StepCompletedEvent)} is called after execution finishes (success or failure).</li>
 *     <li>{@link #getExecutedStepsInContextInOrderOfExecutionStarted(UUID)} must return a stable history view.</li>
 * </ol>
 * <p>
 * A practical implementation pattern is shown in {@code TestPersistence}:
 * write start/completed events and reconstruct {@link StepExecutedInfo} by {@code stepId}.
 */
@NullMarked
public interface KanalarzPersistence {

    /**
     * Event emitted before a step method (or rollback method) executes.
     * @param contexts active context stack (root to leaf)
     * @param stepId unique step execution id (UUIDv7 generated by Kanalarz)
     * @param parentStepId optional parent step id for nested step calls
     * @param stepIsRollbackFor optional rollforward step id when this execution is a rollback
     * @param metadata context metadata
     * @param stepIdentifier globally unique step identifier
     * @param description optional parsed step description
     * @param serializedParameters serialized step call parameters
     * @param isFallible whether the executed step is fallible
     * @param isRollbackMarker whether this execution is rollback-only marker step
     * @param executionPath deterministic execution path for replay matching
     */
    record StepStartedEvent(
        List<UUID> contexts,
        UUID stepId,
        Optional<UUID> parentStepId,
        Optional<UUID> stepIsRollbackFor,
        Map<String, String> metadata,
        String stepIdentifier,
        @Nullable ParameterizedStepDescription description,
        String serializedParameters,
        boolean isFallible,
        boolean isRollbackMarker,
        String executionPath
    ) {}

    /**
     * Persist the event emitted before step execution.
     * <p>
     * This should be durably stored together with all fields. Later replay/rollback logic depends on this data.
     * @param stepStartedEvent event payload
     */
    void stepStarted(StepStartedEvent stepStartedEvent);

    /**
     * Event emitted after a step method (or rollback method) completes.
     * @param contexts active context stack (root to leaf)
     * @param stepId unique step execution id (UUIDv7 generated by Kanalarz)
     * @param parentStepId optional parent step id for nested step calls
     * @param stepIsRollbackFor optional rollforward step id when this execution is a rollback
     * @param metadata context metadata snapshot
     * @param stepIdentifier globally unique step identifier
     * @param description optional parsed step description
     * @param serializedExecutionResult serialized step result payload
     * @param failed whether execution failed
     * @param isRollbackMarker whether this execution is rollback-only marker step
     * @param executionPath deterministic execution path for replay matching
     */
    record StepCompletedEvent(
        List<UUID> contexts,
        UUID stepId,
        Optional<UUID> parentStepId,
        Optional<UUID> stepIsRollbackFor,
        Map<String, String> metadata,
        String stepIdentifier,
        @Nullable ParameterizedStepDescription description,
        String serializedExecutionResult,
        boolean failed,
        boolean isRollbackMarker,
        String executionPath
    ) {}

    /**
     * Persist the event emitted after step execution.
     * <p>
     * The event should be matched to the earlier started event using {@code stepId}.
     * @param stepCompletedEvent event payload
     */
    void stepCompleted(StepCompletedEvent stepCompletedEvent);

    /**
     * Persisted representation of a completed step or rollback execution.
     * @param contexts context stack associated with execution
     * @param stepId unique step execution id (UUIDv7 generated by Kanalarz)
     * @param stepIdentifier globally unique step identifier
     * @param serializedExecutionResult serialized step result payload
     * @param parentStepId optional parent step id
     * @param wasRollbackFor optional rollforward step id if this is a rollback execution
     * @param failed whether execution failed
     * @param executionPath deterministic execution path used by replay
     */
    record StepExecutedInfo(
        List<UUID> contexts,
        UUID stepId,
        String stepIdentifier,
        String serializedExecutionResult,
        Optional<UUID> parentStepId,
        Optional<UUID> wasRollbackFor,
        boolean failed,
        String executionPath
    ) {}

    /**
     * Get a list of executed steps in the context with the given id, or within any nested contexts inside of that one.
     * Sorted by execution start time ascending.
     * <p>
     * Kanalarz uses this data for rollback and resume replay, so ordering and execution path values must be preserved.
     * <p>
     * Ordering contract:
     * <ul>
     *     <li>Return both rollforward and rollback executions.</li>
     *     <li>Return only steps that belong to {@code contextId} (including nested contexts under it).</li>
     *     <li>Return in the same order as original execution start order.</li>
     * </ul>
     * Step ids generated by Kanalarz are UUIDv7 ({@link Kanalarz#timeOrderedEpochPlus1()}), so they are
     * lexicographically sortable and can be used to recover execution-start ordering.
     * <p>
     * @param contextId context id to query
     * @return ordered list of persisted step executions
     */
    List<StepExecutedInfo> getExecutedStepsInContextInOrderOfExecutionStarted(UUID contextId);
}
